data:
  raw_path: "data/cars.csv"
  prepared_path: "data/df_clear.csv"
  train_path: "data/train.csv"
  test_path: "data/test.csv"

split:
  test_size: 0.2

model:
  output_path: "models/rf_cars.pkl"
  params:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, 30]
    max_features: ["log2", "sqrt"]
    min_samples_leaf: [1, 2, 4]
    min_samples_split: [2, 5, 10]
